membersrvc:
 extends:
  file: membersrvc.yaml
  service: membersrvc
 container_name: membersrvc
 hostname: membersrvc

vp0:
 extends:
  file: vp-pbft.yaml
  service: vp-pbft
 container_name: vp0
 hostname: vp0
 ports:
   - "8000:8000"
   - "7050:7050"
   - "7053:7053"
 environment:
   - CORE_LOGGING_LEVEL=INFO
   - CORE_PEER_ID=vp0
   - CORE_PEER_PKI_ECA_PADDR=membersrvc:7054
   - CORE_PEER_PKI_TCA_PADDR=membersrvc:7054
   - CORE_PEER_PKI_TLSCA_PADDR=membersrvc:7054
   - CORE_SECURITY_ENROLLID=test_vp0
   - CORE_SECURITY_ENROLLSECRET=MwYpmSRjupbT
 links:
   - membersrvc

vp1:
 extends:
  file: vp-pbft.yaml
  service: vp-pbft
 container_name: vp1
 hostname: vp1
 environment:
   - CORE_PEER_DISCOVERY_ROOTNODE=vp0:7051
   - CORE_LOGGING_LEVEL=INFO
   - CORE_PEER_ID=vp1
   - CORE_PEER_PKI_ECA_PADDR=membersrvc:7054
   - CORE_PEER_PKI_TCA_PADDR=membersrvc:7054
   - CORE_PEER_PKI_TLSCA_PADDR=membersrvc:7054
   - CORE_SECURITY_ENROLLID=test_vp1
   - CORE_SECURITY_ENROLLSECRET=5wgHK9qqYaPy
 links:
   - membersrvc
   - vp0

vp2:
 extends:
  file: vp-pbft.yaml
  service: vp-pbft
 container_name: vp2
 hostname: vp2
 environment:
   - CORE_PEER_DISCOVERY_ROOTNODE=vp0:7051 
   - CORE_LOGGING_LEVEL=INFO
   - CORE_PEER_ID=vp2
   - CORE_PEER_PKI_ECA_PADDR=membersrvc:7054
   - CORE_PEER_PKI_TCA_PADDR=membersrvc:7054
   - CORE_PEER_PKI_TLSCA_PADDR=membersrvc:7054
   - CORE_SECURITY_ENROLLID=test_vp2
   - CORE_SECURITY_ENROLLSECRET=vQelbRvja7cJ
 links:
   - vp0
   - membersrvc


vp3:
 extends:
  file: vp-pbft.yaml
  service: vp-pbft
 container_name: vp3
 hostname: vp3
 environment:
   - CORE_PEER_DISCOVERY_ROOTNODE=vp0:7051 
   - CORE_LOGGING_LEVEL=INFO
   - CORE_PEER_ID=vp3
   - CORE_PEER_PKI_ECA_PADDR=membersrvc:7054
   - CORE_PEER_PKI_TCA_PADDR=membersrvc:7054
   - CORE_PEER_PKI_TLSCA_PADDR=membersrvc:7054
   - CORE_SECURITY_ENROLLID=test_vp3
   - CORE_SECURITY_ENROLLSECRET=9LKqKH5peurL
 links:
   - membersrvc
   - vp0

