nvp0:
 extends:
  file: vp-pbft.yaml
  service: vp-pbft
 container_name: nvp0
 hostname: nvp0
 environment:
   - CORE_PEER_DISCOVERY_ROOTNODE=172.22.28.134:7051
   - CORE_LOGGING_LEVEL=INFO
   - CORE_PEER_ID=np0
   - CORE_PEER_PKI_ECA_PADDR=172.22.28.134:7054
   - CORE_PEER_PKI_TCA_PADDR=172.22.28.134:7054
   - CORE_PEER_PKI_TLSCA_PADDR=172.22.28.134:7054
   - CORE_SECURITY_ENROLLID=test_nvp1
   - CORE_SECURITY_ENROLLSECRET=DcYXuRSocuqd
 net: "host"

