membersrvc:
 extends:
  file: membersrvc.yaml
  service: membersrvc
 environment:
   - MEMBERSRVC_SERVER_PORT=172.22.28.125:7054
 container_name: membersrvc
 hostname: membersrvc
 net: "host"

vp0:
 extends:
  file: vp-pbft.yaml
  service: vp-pbft
 container_name: vp0
 hostname: vp0
 environment:
   - CORE_LOGGING_LEVEL=INFO
   - CORE_PEER_ID=vp0
   - CORE_PEER_PKI_ECA_PADDR=172.22.28.125:7054
   - CORE_PEER_PKI_TCA_PADDR=172.22.28.125:7054
   - CORE_PEER_PKI_TLSCA_PADDR=172.22.28.125:7054
   - CORE_SECURITY_ENROLLID=test_vp0
   - CORE_SECURITY_ENROLLSECRET=MwYpmSRjupbT
 net: "host"

